version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: chiper-nestjs-api-template
    restart: 'no'
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: nestjs-api-template