pipeline {
    agent any 
    stages {
        stage('Build') {
            steps {
                echo 'Building...'
                // sh 'docker build -t my-image .'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing...'
                // echo '${env.TEST_JENKINS_VAR}'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying...'
            }
        }
        stage('Publish') {
            steps {
                // sh 'docker login -u my-username -p my-password'
                // sh 'docker tag my-image my-username/my-repo:my-tag'
                // sh 'docker push my-username/my-repo:my-tag'
            }
        }
    }
}